### ISSUE TITLE
How long is the old otp code valid?

### ISSUE THREAD

**Issue by mrshawn191** [aerogear/aerogear-otp-java#27]
It seems its longer than the 30 secs configurered.. Any explanation how long it should be valid?

**Comment by tovine** [comment]
Well it has to be valid a bit longer than the exact window, to compensate for clock skew (i.e. if the server clock is out of sync with the client trying to authenticate)…
From what I can see [in the main file](https://github.com/aerogear/aerogear-otp-java/blob/master/src/main/java/org/jboss/aerogear/security/otp/Totp.java#L104) this is configurable, but the default is to check against the current and previous interval; which makes the code valid for a total of 60 seconds?

**Comment by mrshawn191** [comment]
Ok thanks that makes sense.
